// Session-type-specific vocabulary. A poll's participant votes, a quiz's
// participant answers, a comments session's participant comments. Keep every
// participant-facing and organizer-facing string derived from here instead of
// hardcoding "vote"/"poll" so quiz screens stop borrowing poll language.
const COPY = {
  poll: {
    typeLabel: 'Voting poll',
    verb: 'vote',
    verbGerund: 'voting',
    verbPast: 'voted',
    noun: 'vote',
    nounPlural: 'votes',
    loadingTitle: 'Loading poll...',
    loadingSubtitle: 'Please wait while we prepare your voting experience.',
    notFoundTitle: 'Poll Not Found',
    resultsTitle: 'Poll Results',
    instructionsTitle: 'Voting Instructions',
    submittedMessage: 'Vote recorded. The next question will appear when the host moves on.',
    closedMessage: 'Voting is closed for this question. The next one will appear when the host moves on.',
    anonymousNote: 'Your vote is anonymous and cannot be changed after submission',
    joinCta: 'Join and vote',
    urlLabel: 'Voting URL',
    lockedLabel: 'Locked after the first vote',
  },
  quiz: {
    typeLabel: 'Quiz',
    verb: 'answer',
    verbGerund: 'answering',
    verbPast: 'answered',
    noun: 'answer',
    nounPlural: 'answers',
    loadingTitle: 'Loading quiz...',
    loadingSubtitle: 'Please wait while we prepare your quiz.',
    notFoundTitle: 'Quiz Not Found',
    resultsTitle: 'Quiz Results',
    instructionsTitle: 'Quiz Instructions',
    submittedMessage: 'Answer locked. Results appear when the host reveals them.',
    closedMessage: 'This question is locked. The next one will appear when the host moves on.',
    anonymousNote: 'Your answer is recorded under your name/ID and cannot be changed after submission',
    joinCta: 'Join and answer',
    urlLabel: 'Quiz URL',
    lockedLabel: 'Locked after the first answer',
  },
  comments: {
    typeLabel: 'Image & comments',
    verb: 'comment',
    verbGerund: 'commenting',
    verbPast: 'commented',
    noun: 'comment',
    nounPlural: 'comments',
    loadingTitle: 'Loading session...',
    loadingSubtitle: 'Please wait while we prepare the session.',
    notFoundTitle: 'Session Not Found',
    resultsTitle: 'Comments',
    instructionsTitle: 'Instructions',
    submittedMessage: 'Comment recorded. The next image will appear when the host moves on.',
    closedMessage: 'Commenting is closed for this image. The next one will appear when the host moves on.',
    anonymousNote: 'Your comment is recorded under your name/ID and cannot be changed after submission',
    joinCta: 'Join and comment',
    urlLabel: 'Session URL',
    lockedLabel: 'Locked after the first comment',
  },
  wheel: {
    typeLabel: 'Wheel of Fortune',
    verb: 'join',
    verbGerund: 'joining',
    verbPast: 'joined',
    noun: 'entry',
    nounPlural: 'entries',
    loadingTitle: 'Loading wheel...',
    loadingSubtitle: 'Please wait while we load the wheel.',
    notFoundTitle: 'Wheel Not Found',
    resultsTitle: 'Spins',
    instructionsTitle: 'Instructions',
    submittedMessage: '',
    closedMessage: '',
    anonymousNote: 'Your name goes on the wheel and is visible to the organizer',
    joinCta: 'Join the wheel',
    urlLabel: 'Wheel URL',
    lockedLabel: 'Locked after the first spin',
  },
  treasure_hunt: {
    typeLabel: 'Treasure hunt',
    verb: 'scan',
    verbGerund: 'scanning',
    verbPast: 'scanned',
    noun: 'clue',
    nounPlural: 'clues',
    loadingTitle: 'Loading clue...',
    loadingSubtitle: 'Please wait while we fetch this clue.',
    notFoundTitle: 'Clue Not Found',
    resultsTitle: 'Clues',
    instructionsTitle: 'Instructions',
    submittedMessage: '',
    closedMessage: '',
    anonymousNote: 'Scanning is anonymous - nothing is recorded about who found this clue',
    joinCta: '',
    urlLabel: 'Clues',
    lockedLabel: 'Clues are added freely; there is nothing to lock',
  },
  wheel: {
    typeLabel: 'Wheel of Fortune',
    verb: 'join',
    verbGerund: 'joining',
    verbPast: 'joined',
    noun: 'entry',
    nounPlural: 'entries',
    loadingTitle: 'Loading wheel...',
    loadingSubtitle: 'Please wait while we load the wheel.',
    notFoundTitle: 'Wheel Not Found',
    resultsTitle: 'Spins',
    instructionsTitle: 'Instructions',
    submittedMessage: "You're on the wheel",
    closedMessage: '',
    anonymousNote: 'Your name goes on the wheel for the whole room to see',
    joinCta: 'Join the wheel',
    urlLabel: 'Join URL',
    lockedLabel: 'Locked after the first spin',
  },
}

export function copyFor(sessionType) {
  return COPY[sessionType] || COPY.poll
}
